name: chuck_example
version: 1.0.0+1
publish_to: "none"
description: "Demonstrates how to use the Chuck Interceptor plugin."

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.11.1
  path_provider: ^2.1.6
  connectivity_plus: ^7.3.1
  chuck_interceptor:
    path: ../

dev_dependencies:
  analysis_lints: ^1.0.9

flutter:

  uses-material-design: true
