include: package:analysis_lints/analysis_options.yaml

formatter:
  page_width: 120

analyzer:
  errors:
    avoid_annotating_with_dynamic: ignore
    discarded_futures: ignore
    document_ignores: ignore
  exclude:
    - build/**

linter:
  rules:
    prefer_if_elements_to_conditional_expressions: true
